{
  "hash": "c2a91fcc9ccaa2eaa5efb938f54af8f4",
  "result": {
    "markdown": "---\ntitle: \"Distributions of Random Variables\"\n---\n\n\n\n\n## Recap Week 04\nWe did week 04 in one day, covering numerous probability basics and doing a few exercises in probability, mostly paper and pencil exercises. We saw three examples of continuous probability distributions: normal, uniform, and F. This week, we'll examine continuous distributions in some more detail.\n\n## Five distributions\nWe previously looked at the normal distribution. In this\nChapter of the textbook, we visit five distributions:\n\n- Normal distribution\n- Geometric distribution\n- Binomial distribution\n- Negative binomial distribution\n- Poisson distribution\n\nTo save time, we will follow the textbook instead of\nlecture notes.\n\nThe following picture illustrates the normal distribution. The\nmound-shaped curve represents the probability density\nfunction and the area between the curve and the horizontal\nline represents the value of the cumulative distribution\nfunction.\n\n\n::: {.cell engine.opts='{\"extra.preamble\":[\"\\\\usepackage{pgfplots,stix,pagecolor}\",\"\\\\pgfplotsset{compat=1.18}\"]}'}\n::: {.cell-output-display}\n![](week05_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nConsider a normally distributed nationwide test.\n\nThe total shaded area between the curve and the straight\nhorizontal line can be thought of as one hundred percent\nof that area. In the world of probability, we measure that\narea as 1. The curve is symmetrical, so measure all the\narea to the left of the highest point on the curve as 0.5.\nThat is half, or fifty percent, of the total area between\nthe curve and the horizontal line at the bottom. Instead\nof saying *area between the curve and the horizontal\nline at the bottom*, people usually say *the area\nunder the curve*.\n\nFor any value along the $x$-axis, the $y$-value on the\ncurve represents the value of the probability density\nfunction.\n\nThe area bounded by the vertical line between the $x$-axis\nand the corresponding $y$-value on the curve, though, is\nwhat we are usually interested in because that area\nrepresents probability.\n\n## Notation\n\n$N(\\mu,\\sigma)$ is said to characterize a normal\ndistribution. If we know the *parameters* $\\mu$, the mean,\nand $\\sigma$, the standard deviation, we have a complete\npicture of the normal distribution, namely the height of\nthe hump and its width.\n\n## R function to find probability\nThe `pnorm()` function takes a value of a normally distributed\nrandom variable and returns the probability of that\nvalue or less. The textbook gives an example of the SAT\nand ACT scores. For the SAT, the textbook claims that $\\mu = 1100$ and\n$\\sigma=200$ so we can say the SAT score $x\\sim\nN(1100,200)$ which is read as \"x has the normal\ndistribution with mean 1100 and standard deviation 200.\"\nSuppose you score 1100. What is the probability that\nsomeone will score lower than you?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(1100,mean=1100,sd=200)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5\n```\n:::\n:::\n\n\nThis returns a value of 0.5 or fifty percent. That's\nsomething we can tell without a computer, but for the\nnormal distribution, other values are difficult to\ncompute by hand or guess correctly. For instance,\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(1400,mean=1100,sd=200)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9331928\n```\n:::\n:::\n\n\nreturns a value of 0.9331928, or that 93 percent of\nstudents get below this score.\n\nBecause all probabilities sum to 1, we can use this\ninformation to tell the probability of someone getting a\nhigher score, or the probability of getting a score\nbetween two scores by subtracting the smaller from the\nlarger.\n\nThe textbook gives another example as finding the\nprobability that a particular student scores at least\n1190:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - pnorm(1190,mean=1100,sd=200)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3263552\n```\n:::\n:::\n\n\nwhich returns 32.64 percent. Note that we did not\nexplicitly calculate the $Z$-score that leads to this\nprobability. The $Z$-score is a way of standardizing so\nthat instead of (in this case) $x\\sim N(1100,200)$, we\ncalculate the probability of $Z\\sim N(0,1)$. Here, we\nstandardize by recognizing that $Z=(x-\\mu)/\\sigma$ or\n$(1190-1100)/200=0.45$ and then we can say\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1 - pnorm(0.45,mean=0,sd=1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3263552\n```\n:::\n:::\n\n\nand we get the same answer as above, 32.64 percent.\n\n## Geometric distribution\nFirst we need Bernoulli random variables to understand\nthe Geometric distribution.\n\nIf $X$ is a random variable that takes value 1 with\nprobability of success $p$ and $0$ with probability\n$1 − p$, then $X$ is a Bernoulli random variable with\nmean and standard deviation $\\mu=p$ and\n$\\sigma=\\sqrt{p(1-p)}$. A Bernoulli random variable is a\nprocess with only two outcomes: success or failure.\nFlipping a coin and calling it is an example of\nBernoulli random variable.\n\nNow the question is \"What happens if you flip a coin or\nroll the dice or some other win/lose process many times\nin a row?\"\n\nThe geometric distribution describes how many times it\ntakes to obtain success in a series of Bernoulli trials.\n\nThe textbook (p. 145) gives an example where an\ninsurance company employee is looking for the first\nperson to meet a criteria where the probability of\nmeeting that criteria is 0.7 or seventy percent. We can\ncalculate the probability of 0 failures (the first\nperson, one failure (the second person), and so on,\nusing R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\na <- dgeom(x=0,prob=0.7) # the first person\nb <- dgeom(x=1,prob=0.7) # the second person\nc <- dgeom(x=2,prob=0.7) # the third person\nd <- dgeom(x=3,prob=0.7) # the fourth person\ne <- dgeom(x=4,prob=0.7) # the fifth person\n```\n:::\n\n\nand if we graph these numbers, we'll find they have the\nproperty of exponential decay.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx<-c(a,b,c,d,e)\nplot(x)\n```\n\n::: {.cell-output-display}\n![](week05_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe textbook gives the following definition of the\ngeometric distribution.\n\nIf the probability of a success in one trial is $p$ and\nthe probability of a failure is $1 − p$, then the\nprobability of finding the first success in the $n$th\ntrial is given by $(1 − p)^{n−1}p$. The mean (i.e. expected\nvalue) and standard deviation of this wait\ntime are given by $μ = 1/p$, $σ = \\sqrt{(1 − p)/p^2}$.\n\n## Binomial distribution\nThe textbook says that the binomial distribution is used to describe the number\nof successes in a fixed number of trials. This is\ndifferent from the geometric distribution, which\ndescribed the number of trials we must wait before we\nobserve a success.\n\nSuppose the probability of a single trial being a\nsuccess is $p$. Then the probability of observing exactly\n$k$ successes in $n$ independent trials is given by\n\n$$\n\\binom{n}{k}p^k(1-p)^{n-k}\n$$\n\nand $\\mu=np$, $\\sigma=\\sqrt{np(1-p)}$\n\n### Example using R\n\nThe website [r-tutor.com](https://www.r-tutor.com/elementary-statistics/probability-distributions/binomial-distribution) gives the following problem\nas an example:\n\n#### Problem\n\nSuppose there are twelve multiple choice questions in an\nEnglish class quiz. Each question has five possible\nanswers, and only one of them is correct. Find the\nprobability of having four or fewer correct answers if a student attempts to answer every question at random.\n\n#### Solution\n\nSince only one out of five possible answers is correct, the probability of answering a question correctly by random is 1/5=0.2. We can find the probability of having exactly 4 correct answers by random attempts as follows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(4, size=12, prob=0.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1328756\n```\n:::\n:::\n\n\nwhich returns 0.1329.\n\nTo find the probability of having four or less correct\nanswers by random attempts, we apply the function dbinom\nwith $x = 0,\\ldots,4$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(0, size=12, prob=0.2) +\ndbinom(1, size=12, prob=0.2) +\ndbinom(2, size=12, prob=0.2) +\ndbinom(3, size=12, prob=0.2) +\ndbinom(4, size=12, prob=0.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9274445\n```\n:::\n:::\n\n\nwhich returns 0.9274.\n\nAlternatively, we can use the cumulative probability function for binomial distribution pbinom.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npbinom(4, size=12, prob=0.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9274445\n```\n:::\n:::\n\n\nwhich returns the same answer.\n\n#### Answer\n\nThe probability of four or fewer questions answered correctly by random in a twelve question multiple choice quiz is 92.7%.\n\n## Negative binomial distribution\nThis is a generalization of the geometric distribution,\ndefined in the textbook as follows.\n\nThe negative binomial distribution describes the probability of observing the $k$th success on the\n$n$th trial, where all trials are independent:\n\n$$\nP (\\text{the kth success on the nth trial}) =\n\\binom{n − 1}{k − 1} p^k(1 − p)^{n−k}\n$$\n\nThe value $p$ represents the probability that an\nindividual trial is a success.\n\n## Poisson distribution\nThe textbook defines the Poisson distribution as\nfollows.\n\nSuppose we are watching for events and the number of\nobserved events follows a Poisson distribution with\nrate $λ$. Then\n\n$$\nP (\\text{observe k events}) = \\frac{λ^ke^{−λ}}{k!}\n$$\n\nwhere $k$\nmay take a value 0, 1, 2, and so on, and $k!$ represents\n$k$-factorial, as described on page 150. The letter e ≈\n2.718 is the base of the natural logarithm. The mean and\nstandard deviation of this distribution are λ and √λ,\nrespectively.\n\nThe r-tutor website mentioned above offers the following\nexample of a Poisson distribution problem solved using R.\n\n#### Problem\n\nIf there are twelve cars crossing a bridge per minute on average, find the probability of having seventeen or more cars crossing the bridge in a particular minute.\n\n#### Solution\n\nThe probability of having sixteen or fewer cars crossing the bridge in a particular minute is given by the function ppois.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nppois(16, lambda=12)   # lower tail\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.898709\n```\n:::\n:::\n\n\nwhich returns 0.89871\n\nHence the probability of having seventeen or more cars crossing the bridge in a minute is in the upper tail of the probability density function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nppois(16, lambda=12, lower=FALSE)   # upper tail\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.101291\n```\n:::\n:::\n\n\nwhich returns 0.10129\n\n#### Answer\n\nIf there are twelve cars crossing a bridge per minute on average, the probability of having seventeen or more cars crossing the bridge in a particular minute is 10.1%.\n\n",
    "supporting": [
      "week05_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}