<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Study Guide: Statistics for Informatics - 9&nbsp; Introduction to Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./week10.html" rel="next">
<link href="./week08.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>
#quarto-sidebar .menu-text {
  display: flex;
}
#quarto-sidebar .chapter-number {
  display: block;
  width: 1.5rem;
  text-align: right;
}
#quarto-sidebar .chapter-title {
  display: block;
  padding-left: 8px;
  text-indent: -2px;
  width: 100%;
}
</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./week09.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introduction to Linear Regression</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Study Guide: Statistics for Informatics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to the Course</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Numerical and Visual Data Summaries</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week03.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">More about R and Quarto</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week04.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Introduction to Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Distributions of Random Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week06.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Details of <code>ggplot2</code>; Introduction to Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week07.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">More about Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week08.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inference for Numerical Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week09.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introduction to Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">More Linear Regression; Logistic Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Coping with Time and Joins</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Milestone 4; Take-home Exam</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./week13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Human Computer Interaction Experiments</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#recap-week-8-inference-for-numerical-data" id="toc-recap-week-8-inference-for-numerical-data" class="nav-link active" data-scroll-target="#recap-week-8-inference-for-numerical-data"><span class="header-section-number">9.1</span> Recap week 8: Inference for numerical data</a></li>
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression"><span class="header-section-number">9.2</span> Linear Regression</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">9.2.1</span> Introduction</a></li>
  <li><a href="#correlation" id="toc-correlation" class="nav-link" data-scroll-target="#correlation"><span class="header-section-number">9.2.2</span> Correlation</a></li>
  <li><a href="#least-squares-line" id="toc-least-squares-line" class="nav-link" data-scroll-target="#least-squares-line"><span class="header-section-number">9.2.3</span> Least squares line</a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions"><span class="header-section-number">9.2.4</span> Assumptions</a></li>
  <li><a href="#the-multiple-coefficient-of-determination" id="toc-the-multiple-coefficient-of-determination" class="nav-link" data-scroll-target="#the-multiple-coefficient-of-determination"><span class="header-section-number">9.2.5</span> The Multiple Coefficient of Determination</a></li>
  <li><a href="#categorical-variables" id="toc-categorical-variables" class="nav-link" data-scroll-target="#categorical-variables"><span class="header-section-number">9.2.6</span> Categorical Variables</a></li>
  <li><a href="#outliers" id="toc-outliers" class="nav-link" data-scroll-target="#outliers"><span class="header-section-number">9.2.7</span> Outliers</a></li>
  </ul></li>
  <li><a href="#inference-for-linear-regression" id="toc-inference-for-linear-regression" class="nav-link" data-scroll-target="#inference-for-linear-regression"><span class="header-section-number">9.3</span> Inference for linear regression</a>
  <ul class="collapse">
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals"><span class="header-section-number">9.3.1</span> Confidence intervals</a></li>
  </ul></li>
  <li><a href="#multiple-regression-intro-chapter-9" id="toc-multiple-regression-intro-chapter-9" class="nav-link" data-scroll-target="#multiple-regression-intro-chapter-9"><span class="header-section-number">9.4</span> Multiple regression intro (Chapter 9)</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Introduction to Linear Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="recap-week-8-inference-for-numerical-data" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="recap-week-8-inference-for-numerical-data"><span class="header-section-number">9.1</span> Recap week 8: Inference for numerical data</h2>
<ul>
<li>Textbook section 7.1 One-sample means with the t-distribution</li>
<li>Textbook section 7.2 Paired data</li>
<li>Textbook section 7.3 Difference of two means</li>
<li>Textbook section 7.4 Power calculations for a difference of means</li>
<li>Textbook section 7.5 Comparing many means with ANOVA</li>
</ul>
</section>
<section id="linear-regression" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="linear-regression"><span class="header-section-number">9.2</span> Linear Regression</h2>
<section id="introduction" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">9.2.1</span> Introduction</h3>
<p>Let’s start with an example. Suppose we know how many times a team has won and we can graph it as follows. I haven’t included a scale on the graph but the underlying numbers of wins are 9, 15, 18, 22.5 (a tie), and 23.</p>
<div class="cell" data-engine.opts="{&quot;extra.preamble&quot;:&quot;\usetikzlibrary{backgrounds}&quot;}">
<div class="cell-output-display">
<p><img src="week09_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" style="width:50.0%"></p>
</div>
</div>
<p>What is our best prediction of the number of wins for a new team, irrespective of any other information. The answer is the mean of this number of wins, 17.5. It’s not a very good prediction but it’s the best we can do, given what little we know. Now suppose we know how much the team spends on player salaries. We’ll call that variable <em>payroll</em> and add it to the graph.</p>
<div class="cell" data-engine.opts="{&quot;extra.preamble&quot;:&quot;\usetikzlibrary{backgrounds}&quot;}">
<div class="cell-output-display">
<p><img src="week09_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" style="width:50.0%"></p>
</div>
</div>
<p>Now we can see a pattern. Teams that spend more win more! But that’s not strictly true because there must be other variables at play. Right now, we don’t know what those variables are. But the best prediction we can make for the number of wins for a given new team depends in part on its payroll. We can now draw a diagonal line through this cloud of points and say that that line represents the best prediction for number of wins, like so.</p>
<div class="cell" data-engine.opts="{&quot;extra.preamble&quot;:&quot;\usetikzlibrary{backgrounds}&quot;}">
<div class="cell-output-display">
<p><img src="week09_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" style="width:50.0%"></p>
</div>
</div>
<p>One immediate question to ask is whether the diagonal line pictured above is the best line. People searched for ways of finding the best line for a long time before the most popular method, least squares, was published in 1805. That is the method used most frequently by software but other methods have emerged since then.</p>
<p>The best line is often called the <em>least squares line</em> and it is characterized by two numbers, the slope and the intercept. The intercept is the height at which it intersects the <em>y</em> axis and the slope is the ratio of its rise (its increaase or decrease on the <em>y</em> axis) over its run (its increase or decrease on the <em>x</em> axis). Both the slope and intercept can be positive or negative. A slope of zero or infinity is meaningless. In the statistics world, the intercept is usually called <span class="math inline">\(\beta_0\)</span>, pronounced beta nought, and the slope is usually called <span class="math inline">\(\beta_1\)</span>, pronounced beta one. The reason we use the numeral one is because additional slopes will be considered when we talk about multiple regression.</p>
<p>The <span class="citation" data-cites="Diez2019">Diez, Çetinkaya-Rundel, and Barr (<a href="references.html#ref-Diez2019" role="doc-biblioref">2019</a>)</span> textbook differs a bit from standard practice, using the Latin letter <em>b</em> in place of the Greek <span class="math inline">\(\beta\)</span>. This works well from my point of view because Latin letters are often used to denote estimates of parameters, while the parameters themselves are denoted by Greek letters. Keep in mind that we’re always working with samples so we’re estimating the true slope and intercept with <span class="math inline">\(b_1\)</span> and <span class="math inline">\(b_0\)</span>. Other statistics books sometimes use <span class="math inline">\(\hat{\beta}\)</span> to refer to estimates, which is kind of cumbersome.</p>
<p>Most of our discussion of regression will focus on this least squares line and how good it is. Keep in mind that the word <em>regression</em> is more general than <em>least squares</em>. There are other methods and applications. Least squares is just the easiest way to introduce regression.</p>
<p>What does the term <em>least squares</em> mean? In the following picture, we have added vertical lines connecting the dots to the least squares line. The squares of the lengths of these lines are the way we measure the quality of the line.</p>
<div class="cell" data-engine.opts="{&quot;extra.preamble&quot;:&quot;\usetikzlibrary{backgrounds}&quot;}">
<div class="cell-output-display">
<p><img src="week09_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" style="width:50.0%"></p>
</div>
</div>
<p>In the following pictures, the prediction line on the right is better than that on the left by an amount proportional to the difference between the total length of pink lines in the two pictures. Notice that both lines represent the very best possible prediction for <em>that</em> set of dots. It’s just that, on the right hand side, there’s a closer correspondence between payroll and wins.</p>
<div class="cell" data-engine.opts="{&quot;extra.preamble&quot;:&quot;\usetikzlibrary{backgrounds}&quot;}">
<div class="cell-output-display">
<p><img src="week09_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="correlation" class="level3" data-number="9.2.2">
<h3 data-number="9.2.2" class="anchored" data-anchor-id="correlation"><span class="header-section-number">9.2.2</span> Correlation</h3>
<p>Correlation is a concept that measures the strength of the linear relationship between two variables. We usually use Pearson’s correlation coefficient, <span class="math inline">\(r\)</span>, to measure this kind of relationship. Note that our textbook uses <span class="math inline">\(R\)</span> instead of <span class="math inline">\(r\)</span> to denote this relationship. This is unfortunate, because almost every other statistics book makes a distinction between <span class="math inline">\(R\)</span> as the <em>multiple correlation coefficient</em> and <span class="math inline">\(r\)</span> as Pearson’s correlation coefficient. They happen to be identical in the case of one <span class="math inline">\(x\)</span> and one <span class="math inline">\(y\)</span>, but soon we will consider the case of more than one <span class="math inline">\(x\)</span>, where they differ.</p>
<p><span class="math display">\[r=\frac{1}{n-1}\sum^n_{i=1}\frac{x_i-\bar{x}}{s_x}\frac{y_i-\bar{y}}{s_y}\]</span></p>
</section>
<section id="least-squares-line" class="level3" data-number="9.2.3">
<h3 data-number="9.2.3" class="anchored" data-anchor-id="least-squares-line"><span class="header-section-number">9.2.3</span> Least squares line</h3>
<p><span class="citation" data-cites="Diez2019">Diez, Çetinkaya-Rundel, and Barr (<a href="references.html#ref-Diez2019" role="doc-biblioref">2019</a>)</span> gives the following formulas for finding the least squares line.</p>
<ol type="1">
<li>Find the slope.</li>
</ol>
<p><span class="math display">\[b_1=\frac{s_y}{s_x}r\]</span></p>
<ol start="2" type="1">
<li>Find the intercept.</li>
</ol>
<p><span class="math display">\[b_0=\bar{y}-b_1\bar{x}\]</span></p>
<p>Typically, you use software to identify these numbers. For example, consider the payroll / wins example from above, calculated in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>y<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">9</span>,<span class="dv">18</span>,<span class="dv">15</span>,<span class="dv">23</span>,<span class="fl">22.5</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>x<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">10</span>,<span class="dv">15</span>,<span class="dv">20</span>,<span class="dv">25</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(y<span class="sc">~</span>x))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x)

Residuals:
   1    2    3    4    5 
-2.1  3.7 -2.5  2.3 -1.4 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)   7.9000     3.4039   2.321   0.1030  
x             0.6400     0.2053   3.118   0.0526 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.246 on 3 degrees of freedom
Multiple R-squared:  0.7642,    Adjusted R-squared:  0.6856 
F-statistic: 9.722 on 1 and 3 DF,  p-value: 0.05256</code></pre>
</div>
</div>
<p>I input the number of wins as <span class="math inline">\(y\)</span> and the amount of the payroll as <span class="math inline">\(x\)</span>. Then I constructed a linear model of <span class="math inline">\(y\)</span> explained by <span class="math inline">\(x\)</span>. The <code>lm()</code> function constructs a linear model and the tilde character (<span class="math inline">\(\sim\)</span>) separates the response variable <span class="math inline">\(y\)</span> from the explanatory variable <span class="math inline">\(x\)</span>. The <code>summary()</code> function is wrapped around the <code>lm()</code> function to provide the most commonly accessed values of the output of the <code>lm()</code> function.</p>
<p>The first value output by <code>summary()</code> is the <em>call</em>. This simply shows the formula entered, which in this case was <span class="math inline">\(y\sim x\)</span>.</p>
<p>The next value output by <code>summary()</code> is a list of <em>residuals</em>. These are the differences between the predicted values and the actual values of wins.</p>
<p>The third value output by <code>summary()</code> is the <em>coefficients</em> table. The <span class="math inline">\(b\)</span> values are listed in the <code>Estimate</code> column. Instead of being named <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> they are called (Intercept) and x. The remainder of this table consists of statistics about them. The second column is standard error, the third column is the <span class="math inline">\(t\)</span>-statistic, which is the ratio of the estimate to its standard error. The third column is the <span class="math inline">\(p\)</span>-value, which is the probability of seeing the preceding <span class="math inline">\(t\)</span>-statistic or a larger one if the null hypothesis is true. The null hypothesis here is that <span class="math inline">\(x\)</span> does not predict <span class="math inline">\(y\)</span>.</p>
<p>The last column in the coefficents table contains the significance codes. In this case, <span class="math inline">\(x\)</span> gets a significance code of dot (.). Below the coefficients table is a legend for the significance codes. That tells us that dot means that the <span class="math inline">\(p\)</span>-value for <span class="math inline">\(x\)</span> is below 0.1. The blank in the other row tells us that the significance code for the intercept is less than 1, which it must be because probabilities can be no larger than 1.</p>
<p>Below the coefficients table we see four important values expressed - Multiple R-squared, which is identical to <span class="math inline">\(r^2\)</span> above, - Adjusted R-squared, which we will discuss when we discuss multiple linear regression, - the F-statistic, which we will also discuss under multiple linear regression, and - the <span class="math inline">\(p\)</span>-value of the F-statistic.</p>
<p>These latter values are all more interesting in the case of multiple linear regression. For simple linear regression we have enough information in the body of the coefficients table to make a judgment about whether the linear model <span class="math inline">\(y\sim x\)</span> is sufficient to explain a team’s wins. That judgment depends on whether we are being casual, in which case the model is sufficient, or whether we have money riding on it, in which case the model is just barely insufficient.</p>
</section>
<section id="assumptions" class="level3" data-number="9.2.4">
<h3 data-number="9.2.4" class="anchored" data-anchor-id="assumptions"><span class="header-section-number">9.2.4</span> Assumptions</h3>
<p>Bear in mind that we make four big assumptions in using this model at all. The assumptions are mentioned in the book as follows.</p>
<ul>
<li>Linearity: the data show a linear trend, identified by a scatterplot for instance</li>
<li>Normally distributed residuals: identified by a Q-Q plot, to be described later</li>
<li>Constant variability: <span class="math inline">\(x\)</span> does not vary more or less depending on <span class="math inline">\(y\)</span></li>
<li>Independent observations: there is not a pattern like seasonality or growth or decline in the underlying phenomenon being analyzed (special statistics tools are used for that)</li>
</ul>
<p>Most textbooks use more technical terms for these concepts, especially homoscedasticity for constant variability and heteroscedasticity for non-constant variability. This book just doesn’t want to introduce too much terminology.</p>
<p>The most common assumptions violated in my experience are the first and third. There is often a curvilinear pattern in data that is not captured by a linear model. Also, graphs of data often exhibit a pattern like the cross-section of a horn, which is non-constant variability or heteroscedasticity.</p>
</section>
<section id="the-multiple-coefficient-of-determination" class="level3" data-number="9.2.5">
<h3 data-number="9.2.5" class="anchored" data-anchor-id="the-multiple-coefficient-of-determination"><span class="header-section-number">9.2.5</span> The Multiple Coefficient of Determination</h3>
<p><span class="math inline">\(R^2\)</span> is the most common measure of the strength of a linear relationship, partly because it varies between 0 and 1. It is the proportion of variability in the data explained by the model. It is very domain dependent. For a lot of cases, anything below 0.8 indicates a poor fit. On the other hand, there are areas of physics where 0.1 explains enough of the data to be valuable. You have to consider the domain when evaluating <span class="math inline">\(R^2\)</span>.</p>
</section>
<section id="categorical-variables" class="level3" data-number="9.2.6">
<h3 data-number="9.2.6" class="anchored" data-anchor-id="categorical-variables"><span class="header-section-number">9.2.6</span> Categorical Variables</h3>
<p>With linear regression, the <span class="math inline">\(y\)</span> variable must NEVER be categorical. If you try to do regression in R with the <span class="math inline">\(y\)</span> variable as categorical, you’ll get an error message. There is another procedure you can do, called logistic regression, which has a categorical <span class="math inline">\(y\)</span>. We’ll discuss that later. But for now, bear in mind when you form a model, the outcome is always a continuously valued variable.</p>
<p>On the other hand, any or all of the input variables may be categorical. Note the book’s example of Mario Kart sales. The categorical variable <code>condition</code> has two <em>levels</em> or categories, whether the game is new or used. The outcome variable is the price, which is of course a continuous variable. When you input a categorical variable in R, it automatically encodes it as a number. In the Mario Kart case, the numbers are zero and one. The <code>condition</code> new is shown in the same place on the R output as <span class="math inline">\(b_1\)</span> and the <code>condition</code> used is shown as the intercept. The main idea to understand here is the <em>difference</em> between the two, where the used <code>condition</code> is zero and the new <code>condition</code> is the difference between the price of new and used.</p>
</section>
<section id="outliers" class="level3" data-number="9.2.7">
<h3 data-number="9.2.7" class="anchored" data-anchor-id="outliers"><span class="header-section-number">9.2.7</span> Outliers</h3>
<p>Back in the nineteen seventies, several prominent statisticians said that statistics needed visualization. Their influece is actually responsible for my teaching visualization in this course. One of them, Francis Anscombe, published a data frame that showed how misleading elementary statistics can be without visualization. This data frame has come to be called Anscombe’s quartet and it is often shown to students. Here it is.</p>
<div class="cell-output-display">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;">x1</th>
<th style="text-align: right;">x2</th>
<th style="text-align: right;">x3</th>
<th style="text-align: right;">x4</th>
<th style="text-align: right;">y1</th>
<th style="text-align: right;">y2</th>
<th style="text-align: right;">y3</th>
<th style="text-align: right;">y4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">10</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">8.04</td>
<td style="text-align: right;">9.14</td>
<td style="text-align: right;">7.46</td>
<td style="text-align: right;">6.58</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">6.95</td>
<td style="text-align: right;">8.14</td>
<td style="text-align: right;">6.77</td>
<td style="text-align: right;">5.76</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">7.58</td>
<td style="text-align: right;">8.74</td>
<td style="text-align: right;">12.74</td>
<td style="text-align: right;">7.71</td>
</tr>
<tr class="even">
<td style="text-align: right;">9</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">8.81</td>
<td style="text-align: right;">8.77</td>
<td style="text-align: right;">7.11</td>
<td style="text-align: right;">8.84</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">8.33</td>
<td style="text-align: right;">9.26</td>
<td style="text-align: right;">7.81</td>
<td style="text-align: right;">8.47</td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">9.96</td>
<td style="text-align: right;">8.10</td>
<td style="text-align: right;">8.84</td>
<td style="text-align: right;">7.04</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">7.24</td>
<td style="text-align: right;">6.13</td>
<td style="text-align: right;">6.08</td>
<td style="text-align: right;">5.25</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">4.26</td>
<td style="text-align: right;">3.10</td>
<td style="text-align: right;">5.39</td>
<td style="text-align: right;">12.50</td>
</tr>
<tr class="odd">
<td style="text-align: right;">12</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">10.84</td>
<td style="text-align: right;">9.13</td>
<td style="text-align: right;">8.15</td>
<td style="text-align: right;">5.56</td>
</tr>
<tr class="even">
<td style="text-align: right;">7</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">4.82</td>
<td style="text-align: right;">7.26</td>
<td style="text-align: right;">6.42</td>
<td style="text-align: right;">7.91</td>
</tr>
</tbody>
</table>
</div>
<p>Each <span class="math inline">\(x,y\)</span> pair of this quartet has the same basic statistics and the exact same least squares line. But look at a visualization of them.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="week09_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The power of outliers can be seen in datasets 3 and 4 and the power of a nonlinear relationship can be seen in dataset 2.</p>
</section>
</section>
<section id="inference-for-linear-regression" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="inference-for-linear-regression"><span class="header-section-number">9.3</span> Inference for linear regression</h2>
<section id="confidence-intervals" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="confidence-intervals"><span class="header-section-number">9.3.1</span> Confidence intervals</h3>
<p>The textbook gives formulas for computing confidence intervals. Another way to do so is to use software, such as R. You can use the <code>confint()</code> function to find confidence intervals for coefficients of a linear model. For example, consider our payroll / wins example above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(<span class="fu">lm</span>(y<span class="sc">~</span>x))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %    97.5 %
(Intercept) -2.93279043 18.732790
x           -0.01324184  1.293242</code></pre>
</div>
</div>
</section>
</section>
<section id="multiple-regression-intro-chapter-9" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="multiple-regression-intro-chapter-9"><span class="header-section-number">9.4</span> Multiple regression intro (Chapter 9)</h2>
<p>Everything we’ve done so far has assumed that we know one piece of information’s relationship to another piece of information. Take the example of teams, where we knew the payroll and want to know the number of wins. Suppose we also knew a number of other statistics that might affect wins. How would we incorporate them? The answer is simple. We <em>add</em> them. Because we’re using a linear equation, that is, the equation of a line to model the data, there’s no reason we can’t add terms to the equation. These terms are additive, meaning that we add each term and each term has a coefficient. So now, our estimate of <span class="math inline">\(y\)</span>, which we call <span class="math inline">\(\hat{y}\)</span>, looks like this for <span class="math inline">\(n\)</span> terms.</p>
<p><span class="math display">\[\hat{y}=b_0+b_1x_1+b_2x_2+\cdots+b_nx_n\]</span></p>
<p>In R, we simply add the column names. For example, consider the built-in data frame <code>mtcars</code> where the outcome variable is <code>mpg</code>. We can construct a model of the relationship between <code>mpg</code> and two input variables we suspect of influencing <code>mpg</code> as follows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(mtcars,<span class="fu">summary</span>(<span class="fu">lm</span>(mpg <span class="sc">~</span> hp<span class="sc">+</span>wt)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp + wt)

Residuals:
   Min     1Q Median     3Q    Max 
-3.941 -1.600 -0.182  1.050  5.854 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 37.22727    1.59879  23.285  &lt; 2e-16 ***
hp          -0.03177    0.00903  -3.519  0.00145 ** 
wt          -3.87783    0.63273  -6.129 1.12e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.593 on 29 degrees of freedom
Multiple R-squared:  0.8268,    Adjusted R-squared:  0.8148 
F-statistic: 69.21 on 2 and 29 DF,  p-value: 9.109e-12</code></pre>
</div>
</div>
<p>The output looks a bit different now. First, there are 32 residuals, so the individual residuals are not listed. Instead, you see summary statistics for the residuals.</p>
<p>Next, look at the coefficients table. There are three rows now, for the intercept, for hp, and for wt. Notice that all three have significance codes at the end of the row. Normally, you shouldn’t be concerned about the significance code for the intercept, but the other two are interesting. The code for hp is two stars, meaning that it is less than 0.01, while the code for wt is 1.12e-06, which is abbreviated scientific notation, meaning to take 1.12 and shift the decimal point six places to the left, giving 0.00000112 as the decimal equivalent.</p>
<p>The Multiple R-squared is 82 percent and the Adjusted R-squared is 81 percent. This is a good sign because the Adjusted R-squared is adjusted for the case where you have included too many variables on the right hand side of the linear model formula. If it’s similar to Multiple R-squared, that means you probably have not included too many variables.</p>
<p>The <span class="math inline">\(F\)</span>-statistic is important now, because of its interpretation. The <span class="math inline">\(F\)</span>-statistic tells you that at least one of the variables is significant, taken in combination with the others. The <span class="math inline">\(t\)</span>-statistics only give the individual contribution of the variables, so it’s possible to have a significant <span class="math inline">\(t\)</span>-statistic without a significant <span class="math inline">\(F\)</span>-statistic. The first thing to check in regression output is the <span class="math inline">\(F\)</span>-statistic. If it’s too small, i.e., has a large <span class="math inline">\(p\)</span>-value, try a different model.</p>
<p>You might think that including more variables results in a strictly better model. This is not true for reasons to be explored later. For now, try including all the variables in the data frame by the shorthand of a dot on the right hand side of the formula.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(mpg <span class="sc">~</span> ., <span class="at">data=</span>mtcars))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ ., data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.4506 -1.6044 -0.1196  1.2193  4.6271 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 12.30337   18.71788   0.657   0.5181  
cyl         -0.11144    1.04502  -0.107   0.9161  
disp         0.01334    0.01786   0.747   0.4635  
hp          -0.02148    0.02177  -0.987   0.3350  
drat         0.78711    1.63537   0.481   0.6353  
wt          -3.71530    1.89441  -1.961   0.0633 .
qsec         0.82104    0.73084   1.123   0.2739  
vs           0.31776    2.10451   0.151   0.8814  
am           2.52023    2.05665   1.225   0.2340  
gear         0.65541    1.49326   0.439   0.6652  
carb        -0.19942    0.82875  -0.241   0.8122  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.65 on 21 degrees of freedom
Multiple R-squared:  0.869, Adjusted R-squared:  0.8066 
F-statistic: 13.93 on 10 and 21 DF,  p-value: 3.793e-07</code></pre>
</div>
</div>
<p>You might find this output a bit surprising. You know from the <span class="math inline">\(F\)</span>-statistic that at least one of the variables is contributing significantly to the model but individually, the contributions seem minimal based on the small <span class="math inline">\(t\)</span>-statistics. The model is only a bit better, explaining 86 percent of the variability in the data, and the adjusted <span class="math inline">\(R^2\)</span> value hasn’t improved at all, suggesting that you may have too many variables.</p>
<p>At this stage, you would probably remove some variables, perhaps by trial and error. How would you do this? You could start by running linear models over and over again. For example, you could construct one linear model for each variable and see which one has the largest contribution. Then you could try adding a second variable from among the remaining variables, and do that with each remaining variable, until you find one that adds the Largest contribution. You could continue in this way until you’ve accounted for all the variables, but would take forever to do. Luckily, R has functions to assist with this process and run regressions for you over and over again. I’m going to demonstrate one of them now for which we have to add the leaps package. I should point out that this involves doing some machine learning which is not strictly in the scope of this class, but will save you a lot of time.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>train.control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">train</span>(mpg <span class="sc">~</span> ., <span class="at">data =</span> mtcars,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">method =</span> <span class="st">"leapBackward"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">tuneGrid =</span> <span class="fu">data.frame</span>(<span class="at">nvmax =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">trControl =</span> train.control</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>                    )</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>m<span class="sc">$</span>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   nvmax     RMSE  Rsquared      MAE   RMSESD RsquaredSD    MAESD
1      1 3.528852 0.8077208 3.015705 1.765926  0.2320177 1.529370
2      2 3.104015 0.8306301 2.507496 1.355870  0.2108183 0.884356
3      3 3.211552 0.8255871 2.700867 1.359334  0.2077318 1.033360
4      4 3.148479 0.8296845 2.630645 1.354017  0.1908016 1.074414
5      5 3.254928 0.8164973 2.737739 1.266874  0.2309531 1.044970
6      6 3.259540 0.8212797 2.749594 1.227337  0.2493678 1.043727
7      7 3.322310 0.8570599 2.787698 1.408879  0.1592820 1.153164
8      8 3.297613 0.8666992 2.744000 1.364396  0.1529011 1.114000
9      9 3.330123 0.8632282 2.751539 1.385199  0.1600841 1.111120
10    10 3.286242 0.8588116 2.715828 1.362054  0.1739366 1.120088</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>m<span class="sc">$</span>bestTune[,<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m<span class="sc">$</span>finalModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Subset selection object
10 Variables  (and intercept)
     Forced in Forced out
cyl      FALSE      FALSE
disp     FALSE      FALSE
hp       FALSE      FALSE
drat     FALSE      FALSE
wt       FALSE      FALSE
qsec     FALSE      FALSE
vs       FALSE      FALSE
am       FALSE      FALSE
gear     FALSE      FALSE
carb     FALSE      FALSE
1 subsets of each size up to 2
Selection Algorithm: backward
         cyl disp hp  drat wt  qsec vs  am  gear carb
1  ( 1 ) " " " "  " " " "  "*" " "  " " " " " "  " " 
2  ( 1 ) " " " "  " " " "  "*" "*"  " " " " " "  " " </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m<span class="sc">$</span>finalModel,m<span class="sc">$</span>bestTune[,<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)          wt        qsec 
  19.746223   -5.047982    0.929198 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(mpg<span class="sc">~</span>wt<span class="sc">+</span>qsec,<span class="at">data=</span>mtcars))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt + qsec, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.3962 -2.1431 -0.2129  1.4915  5.7486 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  19.7462     5.2521   3.760 0.000765 ***
wt           -5.0480     0.4840 -10.430 2.52e-11 ***
qsec          0.9292     0.2650   3.506 0.001500 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.596 on 29 degrees of freedom
Multiple R-squared:  0.8264,    Adjusted R-squared:  0.8144 
F-statistic: 69.03 on 2 and 29 DF,  p-value: 9.395e-12</code></pre>
</div>
</div>
<p>The preceding code uses a process of backward selection of models and arrives at a best model with two variables. Backward selection starts with all the variables and gradually removes the worst one at each iteration.</p>
<p>The following code uses a process of sequential selection, which combines both forward and backward. It takes longer to run, but can result in a better model. In this case, it chooses four variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">train</span>(mpg <span class="sc">~</span> ., <span class="at">data =</span> mtcars,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">method =</span> <span class="st">"leapSeq"</span>,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">tuneGrid =</span> <span class="fu">data.frame</span>(<span class="at">nvmax =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>),</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">trControl =</span> train.control</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>                    )</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>m<span class="sc">$</span>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   nvmax     RMSE  Rsquared      MAE    RMSESD RsquaredSD     MAESD
1      1 3.338459 0.9001241 2.890096 1.0951033  0.1013687 0.9516300
2      2 3.189923 0.8859776 2.582903 0.6838624  0.1267838 0.4331819
3      3 2.941144 0.8620702 2.488212 0.9202376  0.1449517 0.6399695
4      4 2.879207 0.8617366 2.480590 1.0315877  0.1534301 0.8871564
5      5 3.132200 0.8965810 2.747981 1.0959380  0.1336679 0.9911532
6      6 3.010670 0.9150866 2.656875 1.0023198  0.1083813 0.8800647
7      7 2.919346 0.9260098 2.499461 0.8913467  0.1133718 0.7935931
8      8 2.985337 0.9085432 2.585924 0.9516997  0.1248117 0.8376843
9      9 3.022897 0.9194308 2.609043 1.1395931  0.1111588 1.0913428
10    10 3.257194 0.8988626 2.811998 1.3089386  0.1423077 1.2115681</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>m<span class="sc">$</span>bestTune[,<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m<span class="sc">$</span>finalModel)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Subset selection object
10 Variables  (and intercept)
     Forced in Forced out
cyl      FALSE      FALSE
disp     FALSE      FALSE
hp       FALSE      FALSE
drat     FALSE      FALSE
wt       FALSE      FALSE
qsec     FALSE      FALSE
vs       FALSE      FALSE
am       FALSE      FALSE
gear     FALSE      FALSE
carb     FALSE      FALSE
1 subsets of each size up to 4
Selection Algorithm: 'sequential replacement'
         cyl disp hp  drat wt  qsec vs  am  gear carb
1  ( 1 ) " " " "  " " " "  "*" " "  " " " " " "  " " 
2  ( 1 ) "*" "*"  " " " "  " " " "  " " " " " "  " " 
3  ( 1 ) "*" " "  "*" " "  "*" " "  " " " " " "  " " 
4  ( 1 ) " " " "  "*" " "  "*" "*"  " " "*" " "  " " </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m<span class="sc">$</span>finalModel,m<span class="sc">$</span>bestTune[,<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)          hp          wt        qsec          am 
17.44019110 -0.01764654 -3.23809682  0.81060254  2.92550394 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(mpg<span class="sc">~</span>hp<span class="sc">+</span>wt<span class="sc">+</span>qsec<span class="sc">+</span>am,<span class="at">data=</span>mtcars))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ hp + wt + qsec + am, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.4975 -1.5902 -0.1122  1.1795  4.5404 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) 17.44019    9.31887   1.871  0.07215 . 
hp          -0.01765    0.01415  -1.247  0.22309   
wt          -3.23810    0.88990  -3.639  0.00114 **
qsec         0.81060    0.43887   1.847  0.07573 . 
am           2.92550    1.39715   2.094  0.04579 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.435 on 27 degrees of freedom
Multiple R-squared:  0.8579,    Adjusted R-squared:  0.8368 
F-statistic: 40.74 on 4 and 27 DF,  p-value: 4.589e-11</code></pre>
</div>
</div>
<p>Which model is better? The latter model has the best adjusted <span class="math inline">\(R^2\)</span> value. But it also has what appears to be a spurious variable, hp. It could be that hp is contributing indirectly, by being collinear with one of the other variables. Should we take it out and try again or should we accept the two variable model? That depends on several factors.</p>
<p>There is a principle called Occam’s Razor, named after William of Occam (who didn’t invent it, by the way—things often get named after popularizers rather than inventors). The principle states that, if two explanations have the same explanatory power, you should accept the simpler one. In this context, <em>simpler</em> means fewer variables. The tricky part is what is meant by the <em>same</em> explanatory power. Here we have a comparison of 0.8368 adjusted <span class="math inline">\(R^2\)</span> vs 0.8144. Are those close enough to be considered the same? It depends on the context. If you’re a car buyer I would say yes but if you’re a car manufacturer I would say no. Your opinion might differ. It’s easy to teach the mechanics of these methods (even if you don’t think so yet!) but much harder to come up with the insights to interpret them. (Actually, I would probably choose the three variable model of wt, qsec, and am, but you can test that for yourself.)</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-Diez2019" class="csl-entry" role="listitem">
Diez, David, Mine Çetinkaya-Rundel, and Cristopher D Barr. 2019. <em>OpenIntro Statistics, Fourth Edition</em>. self-published. <a href="https://openintro.org/os">https://openintro.org/os</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./week08.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inference for Numerical Data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./week10.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">More Linear Regression; Logistic Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>